language: go

go:
  - "1.11.x"

install: true

before_install:
  - export TZ=America/Chicago
  - curl -L https://git.io/vp6lP | sh 
  - go get github.com/mattn/goveralls

script:
  - GO111MODULE=on go get ./...
  - GO111MODULE=on go mod vendor
  - GO111MODULE=on go test  -v -mod=vendor ./...
  - $GOPATH/bin/gometalinter.v2 --exclude=test --exclude=mock --exclude=vendor --disable-all --enable=errcheck --enable=vet --enable=vetshadow ./...
  - $GOPATH/bin/goveralls -service=travis-ci
