language: go

services:
  - mongodb

go:
  - "1.11.x"

install: true

before_install:
  - export TZ=America/Chicago
  - curl -L https://git.io/vp6lP | sh 
  - go get github.com/mattn/goveralls
  - export MONGO_TEST=mongodb://127.0.0.1:27017
  - export PATH=$(pwd)/bin:$PATH

script:
  - GO111MODULE=on go get ./...
  - GO111MODULE=on go mod vendor
  - GO111MODULE=on go test  -v -mod=vendor ./...
  - ./bin/gometalinter --deadline=120s --exclude=test --exclude=mock --exclude=vendor --disable-all --enable=errcheck --enable=vet --enable=vetshadow --enable=megacheck --enable=ineffassign --enable=varcheck --enable=unconvert --enable=deadcode --enable=interfacer --enable=gotype ./...
  - $GOPATH/bin/goveralls -show -service=travis-ci
