version: '2'

services:
    "auth-example":
        build: 
            context: .
            dockerfile: Dockerfile

        image: umputun/auth-example
        container_name: "auth-example"
        hostname: "auth-example"

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        environment:
            - AEXMPL_GITHUB_CID
            - AEXMPL_GITHUB_CSEC

        ports:
          - "8080:8080" # primary rest server
          - "8084:8084" # local oauth2 server
